# Stiven Saldaña

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## Ejercicio 2: Modelo Vectorial y TF-IDF
## Objetivo de la práctica

### * Comprender el modelo vectorial como base para representar documentos y  consultas.
### * Calcular la matriz TF-IDF para el corpus data/01_corpus_turismo_500.txt

## 1. Importar la data y guardar el corpus en una variable

In [2]:
ruta = '/kaggle/input/03-corpus-turismo-500-txt/01_corpus_turismo_500.txt'
with open(ruta, 'r') as f:
    text = f.read()
text
## en la variable "text" guardo todo mi corpus

'Otavalo es conocido por su mercado indígena y su artesanía Perfecto para rafting.\nLa Laguna Quilotoa destaca por su color turquesa\nVilcabamba atrae visitantes interesados en longevidad y naturaleza Una experiencia inolvidable.\nQuito tiene un centro histórico Patrimonio de la Humanidad Perfecto para surf.\nEcuador es un país megadiverso, ideal para el turismo ecológico\nLos turistas disfrutan las fiestas y gastronomía típica local Perfecto para avistamiento de aves.\nOtavalo es conocido por su mercado indígena y su artesanía Una experiencia inolvidable.\nEl volcán Cotopaxi es un destino de senderismo popular\nEl Parque Nacional Cajas invita a caminatas entre lagunas Ideal para el próximo feriado.\nMindo es famoso por el avistamiento de aves Ideal para el próximo feriado.\nCuenca deslumbra con su arquitectura colonial y gastronomía Una experiencia inolvidable.\nLas Islas Galápagos atraen visitantes por su biodiversidad única Ideal para el próximo feriado.\nGuayaquil sorprende con su 

## 2. Limpieza de datos

In [37]:
## se guarda el el corpus en una lista 
vocabulario = list(set(text.lower().replace('\n',' ').replace('.',' ').replace(',',' ').split()))
vocabulario

['islas',
 'experiencia',
 'laguna',
 'amazonía',
 'famoso',
 'parque',
 'ofrece',
 'longevidad',
 'surf',
 'indígena',
 'gastronomía',
 'durante',
 'centro',
 'turquesa',
 'feriado',
 'visitar',
 'ecuatoriana',
 'perfecto',
 'es',
 'las',
 'sorprende',
 'y',
 'a',
 'histórico',
 'santa',
 'mercado',
 'avistamiento',
 'sorprendente',
 'país',
 'surfistas',
 'famosas',
 'nacional',
 'increíble',
 'naturaleza',
 'única',
 'mindo',
 'quilotoa',
 'cotopaxi',
 'ideal',
 'visitan',
 'llena',
 'arquitectura',
 'por',
 'nocturna',
 'fiestas',
 'el',
 'como',
 'invita',
 'vilcabamba',
 'cajas',
 'deportes',
 'turismo',
 'próximo',
 'turistas',
 'senderismo',
 'playas',
 'volcán',
 'feriados',
 'deslumbra',
 'colonial',
 'muchos',
 'baños',
 'disfrutan',
 'aves',
 'atraen',
 'inolvidable',
 'se',
 'malecón',
 'un',
 'agua',
 'galápagos',
 'conecta',
 'su',
 'montañita',
 'lagunas',
 'canopy',
 'auténtico',
 'megadiverso',
 'en',
 'spondylus',
 'tiene',
 'ecológico',
 'destaca',
 'visitantes',
 '

In [40]:
## ver longitud de la variable vocabulario
N = len(vocabulario)
N

118

## 3. Generacion del corpus

In [21]:
## aqui se divide el corpus en documentos en donde cada salto de linea o "\n" es un indicador para separar
corpus = text.split('\n')
corpus

['Otavalo es conocido por su mercado indígena y su artesanía Perfecto para rafting.',
 'La Laguna Quilotoa destaca por su color turquesa',
 'Vilcabamba atrae visitantes interesados en longevidad y naturaleza Una experiencia inolvidable.',
 'Quito tiene un centro histórico Patrimonio de la Humanidad Perfecto para surf.',
 'Ecuador es un país megadiverso, ideal para el turismo ecológico',
 'Los turistas disfrutan las fiestas y gastronomía típica local Perfecto para avistamiento de aves.',
 'Otavalo es conocido por su mercado indígena y su artesanía Una experiencia inolvidable.',
 'El volcán Cotopaxi es un destino de senderismo popular',
 'El Parque Nacional Cajas invita a caminatas entre lagunas Ideal para el próximo feriado.',
 'Mindo es famoso por el avistamiento de aves Ideal para el próximo feriado.',
 'Cuenca deslumbra con su arquitectura colonial y gastronomía Una experiencia inolvidable.',
 'Las Islas Galápagos atraen visitantes por su biodiversidad única Ideal para el próximo fer

In [36]:
## en una caribale N se guarda el # de documentos total
len(corpus)
 

501

In [23]:
## se muestra el primer documento del corpus
##doc = corpus[0]
##doc 

## Definimos una funcion para calcular el TF (Termine Frequecy)

In [24]:
def get_tf(doc):
    vec = []
    palabras_doc = doc.lower().replace('.','').replace(',','').split()
    for word in vocabulario:
        cont = palabras_doc.count(word)
        vec.append(cont)
    return np.array(vec)

In [25]:
# guardamos en una variable "x" el primer documento
x = get_tf(corpus[0])
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0])

In [26]:
## se genera la matriz TF en donde para todos los documentos del corpus
## se guarda la lista creada con "get_tf(doc)" en un vector y luego se
## separa cada vector y se coloca otro despues de otro para crear una matriz
corpus_vec = []
for doc in corpus:
    doc_vec = get_tf(doc)
    corpus_vec.append(doc_vec)

In [28]:
## espacio vectorial TF
print(corpus_vec)

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0]), array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [29]:
## se convierte la matrix TF a una tipo Numpy para optimizar operaciones
matriz_tf = np.array(corpus_vec)
matriz_tf

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
# Esto cuenta las columnas (términos) donde hay al menos una aparición y suma 
# el numero de apariciones que hay por columna
dft = np.sum((matriz_tf > 0).astype(int), axis=0)
dft

array([ 33,  96,  32,  27,  38,  37,  32,  27,  17,  33,  66,  54,  20,
        32, 138,  92,  27, 100, 119,  65,  33, 159,  37,  20,  32,  33,
        44,  15,  36,  27,  47,  37,  11,  27,  33,  23,  32,  27, 142,
        27,  27,  34, 121,  33,  32, 219,  79,  37,  27,  37,  32,  36,
       118,  32,  44,  47,  27,  27,  34,  34,  27,  32,  32,  44,  33,
        96,  27,  33, 161,  32,  33,  47, 165,  74,  37,  23,  13,  36,
        27,  47,  20,  36,  32,  60,  33,  27,  33,  20,  16,  59, 323,
        27,  20,  47,  33,  67,  34,  32,  33,  33,  37,  32,  32, 126,
        20,  27,  54,  96,  32,  47, 148,  92,  33,  33,  37,  27,  20,
        36])

## Calculo del vector IDF (Inverse Document Frequency)

In [43]:
# Fórmula IDF: IDF_t = log(N / DF_t)

def get_idf(N, dft):
    return idf_vector

In [53]:
# np.divide realiza la división elemento a elemento: N / dft[i]
idf = np.log(np.divide(N, dft))
idf

array([ 1.27417706,  0.20633643,  1.30494872,  1.47484776,  1.13309846,
        1.15976671,  1.30494872,  1.47484776,  1.93747128,  1.27417706,
        0.58102988,  0.78170058,  1.77495235,  1.30494872, -0.15656906,
        0.24889605,  1.47484776,  0.16551444, -0.00843887,  0.59629735,
        1.27417706, -0.29821958,  1.15976671,  1.77495235,  1.30494872,
        1.27417706,  0.98649499,  2.06263442,  1.18716569,  1.47484776,
        0.92053702,  1.15976671,  2.37278935,  1.47484776,  1.27417706,
        1.63519041,  1.30494872,  1.47484776, -0.18514243,  1.47484776,
        1.47484776,  1.2443241 , -0.02510592,  1.27417706,  1.30494872,
       -0.61838711,  0.40123677,  1.15976671,  1.47484776,  1.15976671,
        1.30494872,  1.18716569,  0.        ,  1.30494872,  0.98649499,
        0.92053702,  1.47484776,  1.47484776,  1.2443241 ,  1.2443241 ,
        1.47484776,  1.30494872,  1.30494872,  0.98649499,  1.27417706,
        0.20633643,  1.47484776,  1.27417706, -0.31071974,  1.30

## Caclulo de la matrix TF-IDF

In [54]:
matriz_tfidf = matriz_tf * idf
matriz_tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.30494872, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.20633643, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.27417706, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])